bases:
- ../../base
configMapGenerator:
- name: lnmp-php-conf-0.0.1
  files:
  - php.ini=config/ini/php.custom.ini
  # - php.ini=config/ini/php.production.ini
  - zz-docker.conf=config/zz-docker.custom.conf
  # - zz-docker.conf=config/zz-docker.production.conf
  - composer.config.json=config/composer/config.custom.json
  # - composer.config.json=config/composer/config.production.json
  - docker.ini=config/conf.d/docker.custom.ini
  # - docker.ini=config/conf.d/docker.production.ini
- name: lnmp-env-0.0.1
  literals:
  - APP_ENV=production
  - APP_LOG=errorlog
  - LOG_CHANNEL=errorlog
  - LNMP_XDEBUG_REMOTE_HOST=192.168.199.100
  - LNMP_XDEBUG_REMOTE_PORT="9001"
  - LNMP_OPCACHE_ENABLE="1"
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: lnmp
    tier: php
