# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: lnmp-redis-data
#   labels:
#     type: local
#     app: lnmp
#     tier: redis
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes: [ "ReadWriteMany" ]
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     # FIXME: use the right IP
#     server: 192.168.199.100
#     path: "/lnmp/redis"
#   storageClassName: slow
#   mountOptions:
#     # - hard
#     # - nfsvers=4.1
#     - nfsvers=4
# ---
# NFS PVC 动态创建 NFS PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-redis-data
  labels:
    app: lnmp
    tier: redis
  annotations:
    # volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
spec:
  accessModes:
    - ReadWriteMany
  # selector:
  #   matchLabels:
  #     app: lnmp
  #     tier: redis
  resources:
    requests:
      storage: 20Gi
  storageClassName: "managed-nfs-storage"
