resources:
- csi-attacher-nfsplugin.yaml
- csi-attacher-rbac.yaml
- csi-nodeplugin-nfsplugin.yaml
- csi-nodeplugin-rbac.yaml
- configMap.yaml
vars:
- name: KUBELET_ROOT
  objref:
    kind: ConfigMap
    name: csi.nfs.conf
    apiVersion: v1
  fieldref:
    fieldpath: data.kubelet_root
