# 请求头包含 foo: bar 路由到 v2，并且会出现 500 错误
# curl -IH "foo: bar" http://wsl2:19749/

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-vs-demo
spec:
  gateways:
  - demo-gw
  hosts:
  - "*"
  http:
  - match:
    - headers:
        foo:
          exact: bar
    fault:
      abort:
        percentage:
          value: 100.0
        httpStatus: 500
    route:
    - destination:
        host: nginx
        subset: v2
  - route:
    - destination:
        host: nginx
        subset: v1
