# 超时
# curl -H "foo: bar" http://wsl2:19749/

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-vs-demo
spec:
  gateways:
  - demo-gw
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: nginx
        subset: v2
    timeout: 0.5s
    fault:
      delay:
        percent: 100
        fixedDelay: 4s
