apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: runsc
handler: runsc # 值与 OCI 配置文件对应
# scheduling:
#   nodeSelector:
#     kubernetes.io/os: 'windows'
#     kubernetes.io/arch: 'amd64'
#     node.kubernetes.io/windows-build: '10.0.17763'
#   tolerations:
#   - effect: NoSchedule
#     key: os
#     operator: Equal
#     value: "windows"

---

apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: runc
handler: runc

---

apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: crun
handler: crun
