on:
  push:
    branches:
      - "master"
  pull_request:

name: CI-CDN

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      LNMP_CN_ENV: false
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: test
          docker_version: "20.10"
      - uses: khs1994-docker/actions-setup-lnmp@master
        with:
          lnmp_branch: "20.10"
          lnmp_services: "nginx mysql php7 redis minio"
          lrew_include: "minio"
      - name: Init LNMP
        run: |
          set -x
          docker-compose --version
          lnmp-docker compose --official
          lnmp-docker services
          docker-compose --version
      - name: Setup S3(Minio)
        run: |
          set -x
          echo "MINIO_ACCESS_KEY=minioadmin" >> $LNMP_PATH/.env
          echo "MINIO_SECRET_KEY=minioadmin" >> $LNMP_PATH/.env
          echo "MINIO_REGION=us-east-1" >> $LNMP_PATH/.env
          echo "MINIO_BROWSER=off" >> $LNMP_PATH/.env
          # echo "LNMP_MINIO_VERSION=latest" >> $LNMP_PATH/.env

          cp $LNMP_PATH/config/nginx/minio.config $LNMP_PATH/config/nginx/minio.conf

          echo "ASSET_URL=https://minio.t.khs1994.com/laravel-docker/frontend-assets" \
              >> $LNMP_PATH/lrew/laravel/.env.development

          cat <<EOF | tee -a $LNMP_PATH/lrew/laravel/.env.development
          AWS_ACCESS_KEY_ID=minioadmin
          AWS_SECRET_ACCESS_KEY=minioadmin
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=laravel
          AWS_USE_PATH_STYLE_ENDPOINT=true
          AWS_ENDPOINT=http://minio:9000
          EOF

          cat $LNMP_PATH/lrew/laravel/.env.development
      - name: Install Laravel
        env:
          ACTIONS_COMPOSER_BIN_PATH: /home/runner/.composer/vendor/bin
        run: |
          set -x
          export PATH=$ACTIONS_COMPOSER_BIN_PATH:$PATH

          lnmp-composer config -g --unset repos.packagist

          cd ..
          lnmp-laravel new laravel

          cp -r laravel-demo/Dockerfile.cdn laravel/

          ls -la laravel

          cd laravel

          patch -p1 < ../laravel-demo/cdn-patch/config-app.patch
          patch -p1 < ../laravel-demo/patch/app-console-kernel.patch

          lnmp-composer require laravel/ui
          lnmp-composer require league/flysystem
          lnmp-composer require league/flysystem-aws-s3-v3
          # 此步骤会重置 webpack.mix.js
          lnmp-php artisan ui vue --auth

          cp -r ../laravel-demo/laravel-patch/. .
          ls -la resources/views

          lnmp-npm i
          lnmp-npm install laravel-mix-versionhash --save
          lnmp-npm run dev
      - name: Test Laravel
        run: |
          set -x
          cd ../laravel

          lnmp-php artisan -V
      - name: Build Docker Image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          set -x

          cd ../laravel

          lnmp-docker up

          export NODE_IP=`ifconfig eth0 | grep "inet" | awk '{ print $2}' | cut -d ':' -f 2`

          docker buildx build --load \
              --add-host minio.local:${NODE_IP} \
              \
              --build-arg NODE_REGISTRY=https://registry.npmjs.org \
              --target=laravel \
              -t khs1994/laravel:8 \
              -f Dockerfile.cdn . \

          docker buildx build --load \
              --add-host minio.local:${NODE_IP} \
              \
              --build-arg NODE_REGISTRY=https://registry.npmjs.org \
              --target=laravel-rootless \
              -t khs1994/laravel:8-rootless \
              -f Dockerfile.cdn . \
      - name: Up LNMP
        run: |
          set -x

          export LNMP_SERVICES='nginx mysql php7 redis minio laravel'
          export LREW_INCLUDE='minio laravel'

          lnmp-docker up
          sleep 30
          lnmp-docker nginx-cli ls /app/laravel-docker/public \
              || cat $LNMP_PATH/log/nginx/error.log
      - name: Connect and Test
        run: |
          docker ps -a

          echo ::group::Test /
            curl -k https://laravel-docker.t.khs1994.com
          echo ::endgroup::

          echo ::group::Test Response
            curl -k https://laravel-docker.t.khs1994.com/test
          echo ::endgroup::

          echo ::group::Test View
            curl -k https://laravel-docker.t.khs1994.com/test/view
          echo ::endgroup::

          echo ::group::Test Queue
            curl -k https://laravel-docker.t.khs1994.com/test/queue
            sleep 2
            curl -k https://laravel-docker.t.khs1994.com/test/queue/result
          echo ::endgroup::

          echo ::group::Test Schedule
            curl -k https://laravel-docker.t.khs1994.com/test/schedule/result
            sleep 55
            curl -k https://laravel-docker.t.khs1994.com/test/schedule/result
          echo ::endgroup::

          docker run -i --rm --entrypoint=sh khs1994/laravel:8 -c "ls -la /app/laravel-docker"

      - name: Connect and Test Rootless
        run: |
          echo 'LNMP_LARAVEL_TAG=8-rootless' >> $LNMP_PATH/.env
          lnmp-docker up

          sleep 30
          docker ps -a

          echo ::group::Test /
            curl -k https://laravel-docker.t.khs1994.com
          echo ::endgroup::

          echo ::group::Test Response
            curl -k https://laravel-docker.t.khs1994.com/test
          echo ::endgroup::

          echo ::group::Test View
            curl -k https://laravel-docker.t.khs1994.com/test/view
          echo ::endgroup::

          echo ::group::Test Queue
            curl -k https://laravel-docker.t.khs1994.com/test/queue
            sleep 2
            curl -k https://laravel-docker.t.khs1994.com/test/queue/result
          echo ::endgroup::

          echo ::group::Test Schedule
            curl -k https://laravel-docker.t.khs1994.com/test/schedule/result
            sleep 55
            curl -k https://laravel-docker.t.khs1994.com/test/schedule/result
          echo ::endgroup::

          echo ::group::Test Rootless
            curl -k https://laravel-docker.t.khs1994.com/test/rootless/result
          echo ::endgroup::

          docker run -i --rm --entrypoint=sh khs1994/laravel:8-rootless -c "ls -la /app/laravel-docker"
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v2
