version: "3.6"

services:
  nfs:
    restart: "no"
    image: erichough/nfs-server
    volumes:
      - nfs-volume:/nfs
    env_file:
      - ./.env.example
      - ./.env
    # cap_add:
    #  - SYS_ADMIN
    privileged: true
    ports:
      # - "111:111"
      # - "111:111/udp"
      # nfs4 only need open 2049 port
      - "2049:2049"
      - "2049:2049/udp"
      # - "20048：20048"
      # - "20048：20048/udp"

volumes:
  nfs-volume:
