variant: fcos
version: 1.0.0
systemd:
  units:
    - name: docker.service
      dropins:
        - name: docker.conf
          contents: |
            [Service]
            # ExecStart=
            # ExecStart=/usr/bin/dockerd \
            #   --host=fd:// \
            #   --exec-opt native.cgroupdriver=systemd

storage:
  files:
    - path:       "/etc/docker/daemon.json"
      mode:       0644
      contents:
        inline: |
          {
            "tlsverify": true,
            "tlscert": "${K8S_ROOT}/certs/docker/server.pem",
            "tlskey": "${K8S_ROOT}/certs/docker/server-key.pem",
            "tlscacert": "${K8S_ROOT}/certs/ca.pem",
            "registry-mirrors" : [
              "https://mirror.baidubce.com",
              "https://hub-mirror.c.163.com"
            ],
            "debug" : true,
            "dns" : [
              "114.114.114.114",
              "8.8.8.8"
            ],
            "experimental" : true
          }
    - path: ${K8S_ROOT}/certs/docker/server.pem
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/docker/server-cert.pem
    - path: ${K8S_ROOT}/certs/docker/server-key.pem
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/docker/server-key.pem
