variant: fcos
version: 1.0.0
systemd:
  units:
    - name: kube-containerd-installer.service
      enabled: true
      contents: |
        [Unit]
        Description=containerd installer
        After=network-online.target
        Wants=network-online.target

        [Service]
        Restart=on-failure
        RestartSec=5
        WorkingDirectory=/tmp

        ExecStartPre=bash -c "if ! [ `/usr/local/bin/kube-containerd --version > /dev/null ; echo $?` = 0 ];then rm -rf /usr/local/bin/kube-containerd; fi"
        ExecStartPre=bash -c "if ! [ -f /usr/local/bin/kube-containerd ];then \
          rm -rf /tmp/bin ;\
          tar -zxvf /opt/.khs1994-docker-lnmp/caches/containerd-${CONTAINERD_VERSION}.linux-amd64.tar.gz \
          -C /tmp ;\
          cp /tmp/bin/containerd /tmp/bin/kube-containerd ; \
          cp /tmp/bin/containerd-shim /tmp/bin/kube-containerd-shim ; \
          cp /tmp/bin/* /usr/local/bin/ ;\
          fi"
        ExecStart=/usr/bin/env echo success
        [Install]
        WantedBy=multi-user.target
    - name: kube-containerd.service
      enabled: true
      contents: |
        [Unit]
        Description=containerd container runtime for kubernetes
        Documentation=https://containerd.io
        After=network-online.target network.target local-fs.target
        Wants=network-online.target
        # Conflicts=xxx.service

        [Service]
        ExecStartPre=-/usr/bin/env mkdir -p /opt/k8s/opt/cni/bin
        ExecStartPre=/usr/bin/env cp -a /usr/libexec/cni/. /opt/k8s/opt/cni/bin
        ExecStartPre=-/usr/bin/env modprobe overlay
        ExecStart=/usr/local/bin/kube-containerd \
                  --config /opt/k8s/etc/kube-containerd/1.4/config.toml
        Type=notify
        KillMode=process
        Delegate=yes
        LimitNOFILE=1048576
        # Having non-zero Limit*s causes performance problems due to accounting overhead
        # in the kernel. We recommend using cgroups to do container-local accounting.
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity

        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /opt/k8s/etc/kube-containerd/1.4/config.toml
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/etc/kube-containerd/1.4/config.toml
    - path: ${K8S_ROOT}/etc/cni/net.d/99-loopback.conf
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/etc/cni/99-loopback.conf
    - path: /opt/.khs1994-docker-lnmp/caches/containerd-${CONTAINERD_VERSION}.linux-amd64.tar.gz
      mode: 0644
      contents:
        compression: null
        source: http://{{SERVER_HOST}}:8080/releases/containerd-${CONTAINERD_VERSION}.linux-amd64.tar.gz
