variant: fcos
version: 1.0.0
systemd:
  units:
storage:
  files:
    - path: ${K8S_ROOT}/bin/kubelet
      mode: 0755
      contents:
        source: http://{{SERVER_HOST}}:8080/kubernetes-release/release/{{KUBERNETES_VERSION}}-linux-amd64/kubernetes/server/bin/kubelet
    - path: ${K8S_ROOT}/bin/mounter
      mode: 0755
      contents:
        source: http://{{SERVER_HOST}}:8080/kubernetes-release/release/{{KUBERNETES_VERSION}}-linux-amd64/kubernetes/server/bin/mounter
    - path: ${K8S_ROOT}/bin/kubeadm
      mode: 0755
      contents:
        source: http://{{SERVER_HOST}}:8080/kubernetes-release/release/{{KUBERNETES_VERSION}}-linux-amd64/kubernetes/server/bin/kubeadm
    - path: ${K8S_ROOT}/bin/generate-kubelet-bootstrap-kubeconfig.sh
      mode: 0755
      contents:
        source: http://{{SERVER_HOST}}:8080/bin/generate-kubelet-bootstrap-kubeconfig.sh
    - path: ${K8S_ROOT}/conf/csr-crb.yaml
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/csr-crb.yaml
