variant: fcos
version: 1.0.0
systemd:
  units:
    - name: kube-apiserver.service
      dropins:
        - name: 10-installer.conf
          contents: |
            [Service]
            # ExecStartPre=bash -c "if ! [ `${K8S_ROOT}/bin/kube-apiserver --version > /dev/null ; echo $?` = 0 ];then rm -rf ${K8S_ROOT}/bin/kube-apiserver; fi"
            # ExecStartPre=bash -c "if ! [ -f ${K8S_ROOT}/bin/kube-apiserver ];then \
            #  curl http://{{SERVER_HOST}}:8080/kubernetes-release/release/{{KUBERNETES_VERSION}}-linux-amd64/kubernetes/server/bin/kube-apiserver \
            #  -o ${K8S_ROOT}/bin/kube-apiserver;fi"
            # ExecStartPre=chmod +x ${K8S_ROOT}/bin/kube-apiserver
            ExecStartPre=-/bin/podman kill kube-apiserver
            ExecStartPre=-/bin/podman rm kube-apiserver
            ExecStartPre=-/bin/podman pull k8s.gcr.io/kube-apiserver:{{KUBERNETES_VERSION}}

            ExecStop=/bin/podman stop kube-apiserver
storage:
  files:
    - path: ${K8S_ROOT}/conf/audit-policy.yaml
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/audit-policy.yaml
    - path: ${K8S_ROOT}/conf/encryption-config.yaml
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/encryption-config.yaml
    - path: ${K8S_ROOT}/certs/proxy-client.pem
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/proxy-client.pem
    - path: ${K8S_ROOT}/certs/proxy-client-key.pem
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/proxy-client-key.pem
    - path: ${K8S_ROOT}/certs/kubernetes.pem
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/kubernetes.pem
    - path: ${K8S_ROOT}/certs/kubernetes-key.pem
      mode: 0644
      contents:
        source: http://{{SERVER_HOST}}:8080/cert/kubernetes-key.pem
    # - path: ${K8S_ROOT}/bin/kube-apiserver
    #   mode: 0755
    #   contents:
    #     source: http://{{SERVER_HOST}}:8080/kubernetes-release/release/{{KUBERNETES_VERSION}}-linux-amd64/kubernetes/server/bin/kube-apiserver
