version: "3.8"

x-common:
  &common
  restart: always
  env_file: ./cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:

  mariadb:
    << : *common
    image: "${LNMP_BUILD_DOCKER_IMAGE_PREFIX:-khs1994}/mariadb:${LNMP_MARIADB_VERSION:-10.5.6}"
    environment:
      # @link https://github.com/docker-library/docs/tree/master/mariadb#environment-variables
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      # MYSQL_ROOT_PASSWORD: ${LNMP_MYSQL_ROOT_PASSWORD:-mytest}
      MYSQL_DATABASE: ${LNMP_MYSQL_DATABASE:-test}
      # MYSQL_USER:
      # MYSQL_PASSWORD:
    ports:
      - "${LNMP_MYSQL_PORT:-127.0.0.1:3306}:3306"
    volumes:
      - ./config/mariadb/${LNMP_MARIADB_CONF:-docker.cnf}:/etc/mysql/conf.d/docker.cnf:ro,cached
      # @link https://github.com/docker-library/docs/tree/master/mariadb#initializing-a-fresh-instance
      - ./scripts/backup/init:/docker-entrypoint-initdb.d:ro,cached
      - type: volume
        source: mariadb-data
        target: ${LNMP_MARIADB_DATA:-/var/lib/mysql}
      - ./log/mariadb:/var/log/mysql:cached
      - ./scripts/backup/mariadb:/backup
    command:
      - mysqld
      - --character-set-server=utf8mb4
    secrets:
      - db_root_password

secrets:
  db_root_password:
    << : *common-label
    file: ./secrets/${LNMP_DB_ROOT_PASSWORD_PATH:-db_root_password.txt}

volumes:
  mariadb-data:
    << : *common-label
