version: "3.8"

x-common:
  &common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  mariadb:
    << : *common
    image: ${LNMP_LIBRARY_NS:-library}/mariadb:${LNMP_MARIADB_VERSION:-10.5.6}
