language: bash

sudo: required

services:
- docker

env:
  global:
  # - DOCKER_COMPOSE_VERSION: 1.17.1
  - TZ: Asia/Shanghai

before_install:
- date
# 升级 Docker 最新 test

- docker --version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) test"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker --version

# 升级最新 Docker Compose

# - docker-compose --version
# - sudo rm /usr/local/bin/docker-compose
# - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION:-1.20.1}/docker-compose-`uname -s`-`uname -m` > docker-compose
# - chmod +x docker-compose
# - sudo mv docker-compose /usr/local/bin
# - docker-compose --version

# 部署公钥

- openssl aes-256-cbc -K $encrypted_3418790a352e_key -iv $encrypted_3418790a352e_iv
  -in cli/khs1994-robot.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

# git config

- git config --global user.name "khs1994-merge-robot"
- git config --global user.email "ai@khs1994.com"

# verify version

- docker --version
- docker-compose --version

#
# common end
#

jobs:
  include:
    - stage: development
      install:
        - sudo rm /usr/local/bin/docker-compose
        - ./lnmp-docker.sh compose --official -f
      script: cli/test development
    - stage: swarm
      script: cli/test swarm
    # - stage: memcached
    #   script:
    # - stage: mysql
    #   script:
    # - stage: redis-master-slave
    #   script:
    # - stage: redis-sentinel
    #   script:
    # - stage: redis-cluster-by-ruby
    #   script:

# stages:
#   - test
#   # - name: deploy
#   #   if: tag =~ ^[0-9.]+$
#   #   if: branch = master
#   #   if: type IN (push, pull_request, api, cron)

branches:
  only:
  - master
  - dev
