language: bash

sudo: required

services:
- docker

env:
  global:
  # - DOCKER_COMPOSE_VERSION=1.17.1
  - TZ=Asia/Shanghai
  - GOPATH=/home/travis/go
  - PATH=/home/travis/go/bin:$PATH
  - TAG=v18.06

before_install:
- date
# 升级 Docker 最新 test

- docker --version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) test"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker --version

# 升级最新 Docker Compose

# - docker-compose --version
# - sudo rm /usr/local/bin/docker-compose
# - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION:-1.20.1}/docker-compose-`uname -s`-`uname -m` > docker-compose
# - chmod +x docker-compose
# - sudo mv docker-compose /usr/local/bin
# - docker-compose --version

# 部署公钥

- openssl aes-256-cbc -K $encrypted_3418790a352e_key -iv $encrypted_3418790a352e_iv
  -in cli/khs1994-robot.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

# git config

- git config --global user.name "khs1994-merge-robot"
- git config --global user.email "ai@khs1994.com"

# verify version

- docker --version
- docker-compose --version

# docker login

- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin

#
# common end
#

#
# github release
#

- sudo apt update ; sudo apt install -y golang
- go get github.com/aktau/github-release
- github-release --help

jobs:
  include:
    - stage: development
      install:
        - sudo rm /usr/local/bin/docker-compose
        - ./lnmp-docker.sh compose --official -f
      script: cli/test development
    - stage: swarm
      script: cli/test swarm
    #
    # wsl-debian
    #

    # Debian9 not support php56
    # use ubuntu 16.04
    - stage: wsl-php-builder-56
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.Dockerfile --build-arg PHP_VERSION=5.6.35 --build-arg OS_TYPE=ubuntu:16.04 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-56
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export DEB_NAME=khs1994-wsl-php_${PHP_VERSION_56}-ubuntu-xenial_amd64.deb
        - docker cp $( docker container ls -a --format {{.ID}} ):/${DEB_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${DEB_NAME}" --file "${DEB_NAME}" -R
    - stage: wsl-php-builder-70
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.Dockerfile --build-arg PHP_VERSION=7.0.29 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-70
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export DEB_NAME=khs1994-wsl-php_${PHP_VERSION_70}-debian-stretch_amd64.deb
        - docker cp $( docker container ls -a --format {{.ID}} ):/${DEB_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${DEB_NAME}" --file "${DEB_NAME}" -R
    - stage: wsl-php-builder-71
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.Dockerfile --build-arg PHP_VERSION=7.1.16 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-71
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export DEB_NAME=khs1994-wsl-php_${PHP_VERSION_71}-debian-stretch_amd64.deb
        - docker cp $( docker container ls -a --format {{.ID}} ):/${DEB_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${DEB_NAME}" --file "${DEB_NAME}" -R
    - stage: wsl-php-builder-72
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.Dockerfile --build-arg PHP_VERSION=7.2.5 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-72
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export DEB_NAME=khs1994-wsl-php_${PHP_VERSION_72}-debian-stretch_amd64.deb
        - docker cp $( docker container ls -a --format {{.ID}} ):/${DEB_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${DEB_NAME}" --file "${DEB_NAME}" -R
    - stage: wsl-php-builder-73
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.Dockerfile --build-arg PHP_VERSION=7.2.5 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-73
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export DEB_NAME=khs1994-wsl-php_${PHP_VERSION_73}-debian-stretch_amd64.deb
        - docker cp $( docker container ls -a --format {{.ID}} ):/${DEB_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${DEB_NAME}" --file "${DEB_NAME}" -R
    # wsl-rhel
    #

    - stage: wsl-php-builder-rhel-56
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.rhel.Dockerfile --build-arg PHP_VERSION=5.6.35 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-rhel-56
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export RPM_NAME=khs1994-wsl-php-${PHP_VERSION_56}-1.el7.centos.x86_64.rpm
        - docker cp $( docker container ls -a --format {{.ID}} ):/${RPM_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${RPM_NAME}" --file "${RPM_NAME}" -R
    - stage: wsl-php-builder-rhel-70
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.rhel.Dockerfile --build-arg PHP_VERSION=7.0.29 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-rhel-70
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export RPM_NAME=khs1994-wsl-php-${PHP_VERSION_70}-1.el7.centos.x86_64.rpm
        - docker cp $( docker container ls -a --format {{.ID}} ):/${RPM_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${RPM_NAME}" --file "${RPM_NAME}" -R
    - stage: wsl-php-builder-rhel-71
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.rhel.Dockerfile --build-arg PHP_VERSION=7.1.16 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-rhel-71
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export RPM_NAME=khs1994-wsl-php-${PHP_VERSION_71}-1.el7.centos.x86_64.rpm
        - docker cp $( docker container ls -a --format {{.ID}} ):/${RPM_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${RPM_NAME}" --file "${RPM_NAME}" -R
    - stage: wsl-php-builder-rhel-72
      script:
        - ./lnmp-docker.sh compose --official -f
        - cd wsl
        # - docker build -t test -f wsl.phpbuilder.rhel.Dockerfile --build-arg PHP_VERSION=7.2.5 .
        - export DOCKER_SERVICE_NAME=wsl-php-builder-rhel-72
        - docker-compose build ${DOCKER_SERVICE_NAME}
        - docker-compose push ${DOCKER_SERVICE_NAME}
        - docker-compose create ${DOCKER_SERVICE_NAME}
        - . .env
        - export RPM_NAME=khs1994-wsl-php-${PHP_VERSION_72}-1.el7.centos.x86_64.rpm
        - docker cp $( docker container ls -a --format {{.ID}} ):/${RPM_NAME} .
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${RPM_NAME}" --file "${RPM_NAME}" -R
    #
    # clusterkit
    #

    # - stage: memcached
    #   script:
    # - stage: mysql
    #   script:
    # - stage: redis-master-slave
    #   script:
    # - stage: redis-sentinel
    #   script:
    # - stage: redis-cluster-by-ruby
    #   script:

    #
    # deg
    #

    - stage: deb
      script:
        - sh cli/build.sh deb ${TAG}
        - export VERSION=$( echo ${TAG} | cut -d "v" -f 2 )
        - export DEB_NAME=khs1994-docker-lnmp_${VERSION}_amd64.deb
        - ls -la cli
        - sudo dpkg -i cli/${DEB_NAME}
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${DEB_NAME}" --file "cli/${DEB_NAME}" -R

    #
    # yum
    #

    - stage: rpm
      install:
        # Don't build rc rpm
        - test $( echo "${TAG}" | grep rc ) && exit 0 || echo
      script:
        - sudo apt install -y rpm
        - sh cli/build.sh rpm ${TAG}
        - export VERSION=$( echo ${TAG} | cut -d "v" -f 2 )
        - export RPM_NAME=$( cd $HOME; ls *.rpm )
        - ls -la ~/*.rpm
        - github-release upload --user khs1994-docker --repo lnmp --tag ${TAG} --name "${RPM_NAME}" --file "${HOME}/${RPM_NAME}" -R

# stages:
#   - test
#   # - name: deploy
#   #   if: tag =~ ^[0-9.]+$
#   #   if: branch = master
#   #   if: type IN (push, pull_request, api, cron)

# stages:
#   - name: deb
#     if: tag =~ ^v
#   - name: rpm
#     if: tag =~ ^v

branches:
  only:
  - master
  - dev
