version: "3.6"

#
# @link https://docs.docker.com/compose/extends/
#

x-common:
  &default-common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:

  mysql:
    << : *default-common
    image: mysql:${KHS1994_LNMP_MYSQL_VERSION:-8.0.3}

  # mariadb:
  #   << : *default-common
  #   image: mariadb:${KHS1994_LNMP_MYSQL_VERSION:-10.3}

  redis:
    << : *default-common
    image: redis:${KHS1994_LNMP_REDIS_VERSION:-4.0}-alpine

  # memcached:
  #   << : *default-common
  #   image: memcached:${KHS1994_LNMP_MEMCACHED_VERSION:-1.5}-alpine

  # rabbitmq:
  #   << : *default-common
  #   image: rabbitmq:${KHS1994_LNMP_RABBITMQ_VERSION:-3.7}-management-alpine

  # postgresql:
  #   << : *default-common
  #   image: postgres:${KHS1994_LNMP_POSTGRESQL_VERSION:-10}-alpine

  # mongodb:
  #   << : *default-common
  #   image: mongo:${KHS1994_LNMP_MONGODB_VERSION:-3.7}

  php7:
    << : *default-common
    image: ${LNMP_DOCKER_IMAGE_PREFIX:-khs1994}/php-fpm:${KHS1994_LNMP_PHP_VERSION:-7.2.4}-alpine3.7

  phpmyadmin:
    << : *default-common
    image: phpmyadmin/phpmyadmin:latest@sha256:065e1c3c82bdbbf3a00168b3dcca7ecb2590dff587ac17ce14177816cdedf5ce

  nginx:
    << : *default-common
    image: ${LNMP_DOCKER_IMAGE_PREFIX:-khs1994}/nginx:${KHS1994_LNMP_NGINX_VERSION:-1.13.11}-tls1.3-stretch

  # httpd:
  #   << : *default-common
  #   image: httpd:${KHS1994_LNMP_HTTPD_VERSION:-2.4}-alpine

networks:
  frontend:
    << : *default-common
  backend:
    << : *default-common

volumes:
  mysql-data:
    << : *default-common
  # mariadb-data:
  #   << : *default-common
  redis-data:
    << : *default-common
  # rabbitmq-data:
  #   << : *default-common
  # postgresql-data:
  #   << : *default-common
  # mongodb-data:
  #   << : *default-common
  zoneinfo-data:
    << : *default-common
  # registry-data:
  #   << : *default-common
  phpmyadmin-data:
    << : *default-common

secrets:
  db_root_password:
    << : *default-common
    file: ./secrets/${DB_ROOT_PASSWORD_PATH:-db_root_password.txt}
