version: "3.6"

#
# @link https://docs.docker.com/compose/extends/
#

x-common:
  &default-common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:

  mysql:
    << : *default-common
    image: mysql:${KHS1994_LNMP_MYSQL_VERSION:-8.0.3}

  mariadb:
    << : *default-common
    image: mariadb:${KHS1994_LNMP_MYSQL_VERSION:-10.3}

  redis:
    << : *default-common
    image: redis:${KHS1994_LNMP_REDIS_VERSION:-4.0}-alpine

  memcached:
    << : *default-common
    image: memcached:${KHS1994_LNMP_MEMCACHED_VERSION:-1.5}-alpine

  rabbitmq:
    << : *default-common
    image: rabbitmq:${KHS1994_LNMP_RABBITMQ_VERSION:-3.7}-management-alpine

  postgresql:
    << : *default-common
    image: postgres:${KHS1994_LNMP_POSTGRESQL_VERSION:-10}-alpine

  mongodb:
    << : *default-common
    image: mongo:${KHS1994_LNMP_MONGODB_VERSION:-4.0}

  php7:
    << : *default-common
    image: ${LNMP_DOCKER_IMAGE_PREFIX:-khs1994}/php-fpm:${KHS1994_LNMP_PHP_VERSION:-7.2.7}-alpine3.7

  phpmyadmin:
    << : *default-common
    image: phpmyadmin/phpmyadmin:latest@sha256:b003fa5555dcb0a305d26aec3935b3a1127179ea8ad9d57685df4e4eab912ca8

  nginx:
    << : *default-common
    image: khs1994/nginx:${KHS1994_LNMP_NGINX_VERSION:-1.15.1}-alpine

  httpd:
    << : *default-common
    image: httpd:${KHS1994_LNMP_HTTPD_VERSION:-2.4}-alpine

networks:
  frontend:
    << : *default-common
  backend:
    << : *default-common

volumes:
  mysql-data:
    << : *default-common
  mariadb-data:
    << : *default-common
  redis-data:
    << : *default-common
  rabbitmq-data:
    << : *default-common
  postgresql-data:
    << : *default-common
  mongodb-data:
    << : *default-common
  zoneinfo-data:
    << : *default-common
  registry-data:
    << : *default-common
  phpmyadmin-data:
    << : *default-common
  gogs-data:
    << : *default-common
  gitlab-data:
    << : *default-common

secrets:
  db_root_password:
    << : *default-common
    file: ./secrets/${DB_ROOT_PASSWORD_PATH:-db_root_password.txt}
