version: "3.7"

services:
  mysql:
    image: mysql:8.0.16

  mariadb:
    image: mariadb:10.4.6

  redis:
    image: redis:5.0.5-alpine

  memcached:
    image: memcached:1.5-alpine

  php:
    image: php:7.3.6-fpm-alpine

  nginx:
    image: nginx:1.17.0-alpine

  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine

  postgresql:
    image: postgres:11.4-alpine

  mongodb:
    image: mongo:4.1.11

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

  httpd:
    image: httpd:2.4.39-alpine

  etcd:
    image: quay.io/coreos/etcd:3.3.12

  minio:
    image: minio/minio:RELEASE.2019-04-18T01-15-57Z

  kong:
    image: kong:1.2.0-alpine

  node:
    image: node:12.5.0-alpine

  go:
    image: golang:1.12.6-alpine

  alpine:
    image: alpine:3.10
