version: "3.5"
services:

  mysql:
    image: mysql:${KHS1994_LNMP_MYSQL_VERSION}

  mariadb:
    image: mariadb:${KHS1994_LNMP_MYSQL_VERSION}

  redis:
    image: redis:${KHS1994_LNMP_REDIS_VERSION}-alpine

  # memcached:
  #   image: memcached:${KHS1994_LNMP_MEMCACHED_VERSION}-alpine

  # rabbitmq:
  #   image: rabbitmq:${KHS1994_LNMP_RABBITMQ_VERSION}-management-alpine

  # postgresql:
  #   image: postgres:${KHS1994_LNMP_POSTGRESQL_VERSION}-alpine

  # mongod:
  #   image: mongo:${KHS1994_LNMP_MONGODB_VERSION}

  php7:
    image: ${LNMP_DOCKER_IMAGE_PREFIX}/php-fpm:${KHS1994_LNMP_PHP_VERSION}-alpine3.7

  phpmyadmin:
    image: phpmyadmin/phpmyadmin

  nginx:
    image: ${LNMP_DOCKER_IMAGE_PREFIX}/nginx:${KHS1994_LNMP_NGINX_VERSION}-tls1.3-stretch

  # apache:
  #   image: httpd:${KHS1994_LNMP_APACHE_VERSION}-alpine
