version: "3.3"
services:

  redis:
    build:
      context: ./dockerfile/redis/
      dockerfile: Dockerfile
    image: "${REGISTRY_URL}/${REGISTRY_USERNAME}/redis:${KHS1994_LNMP_REDIS_VERSION}-alpine"

  php7:
    build:
      context: ./dockerfile/php-fpm/
      dockerfile: Dockerfile
      # build 时的变量，相当于 Dockerfile 中的 ENV
      args:
        buildno: 1
        password: secret
      labels:
        com.khs1994.description: "Extend Official PHP_FPM Docker Image"
        com.khs1994.department: "Chinese"
        com.khs1994.label-with-empty-value: ""
    image: ${REGISTRY_URL}/${REGISTRY_USERNAME}/php-fpm:${KHS1994_LNMP_PHP_VERSION}

  memcached:
    build:
      context: ./dockerfile/memcached/
      dockerfile: Dockerfile
    image: ${REGISTRY_URL}/${REGISTRY_USERNAME}/memcached:${KHS1994_LNMP_MEMCACHED_VERSION}-alpine

  rabbitmq:
    build:
      context: ./dockerfile/rabbitmq/
      dockerfile: Dockerfile
    image: ${REGISTRY_URL}/${REGISTRY_USERNAME}/rabbitmq:${KHS1994_LNMP_RABBITMQ_VERSION}-alpine

  postgresql:
    build:
      context: ./dockerfile/postgresql/
      dockerfile: Dockerfile
    image: ${REGISTRY_URL}/${REGISTRY_USERNAME}/postgres:${KHS1994_LNMP_POSTGRESQL_VERSION}-alpine

  nginx:
    build:
      context: ./dockerfile/nginx/
      dockerfile: Dockerfile
    image: "${REGISTRY_URL}/${REGISTRY_USERNAME}/nginx:${KHS1994_LNMP_NGINX_VERSION}-alpine"
