version: ~> 1.0

language: bash

os: linux
dist: focal
arch: arm64-graviton2
virt: vm
group: edge

services:
- docker

before_install:
- env
# 升级 Docker 最新 stable
- docker --version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) ${DOCKER_CHANNEL}"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker --version
# 升级最新 Docker Compose
# - docker-compose --version
# - sudo rm /usr/local/bin/docker-compose
# - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
# - sudo install -m755 docker-compose /usr/local/bin
# - docker-compose --version
# ubuntu 14.04
# - echo 'DOCKER_OPTS="--experimental"' | sudo tee /etc/default/docker
# - sudo service docker restart
# ubuntu 16.04
- sudo mkdir -p /etc/systemd/system/docker.service.d
- echo -e '[Service]\nExecStart=\nExecStart=/usr/bin/dockerd' | sudo tee /etc/systemd/system/docker.service.d/docker.conf
- echo '{"hosts":["unix:///var/run/docker.sock","tcp://0.0.0.0:2375"],"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo systemctl daemon-reload
- sudo systemctl cat docker
- sudo systemctl restart docker
- sleep 5
- docker run --rm --privileged tonistiigi/binfmt:latest --install all
- ls -la /proc/sys/fs/binfmt_misc
- docker buildx create --name mybuilder
- docker buildx use mybuilder
- docker buildx inspect --bootstrap
- docker buildx ls

script:
  - cp .env.example .env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker-compose build ${PHP_VERSION} --parallel
  # - source tag.sh

  - VCS_REF=`git rev-parse --short HEAD`
  - options="--build-arg VCS_REF=$VCS_REF"
  - echo $options
  - export CACHE_IMAGE=$DOCKER_HUB_USERNAME/php

  - |
    if [ -z "$TRAVIS_TAG" ];then
      if [ "$PHP_VERSION" = 8_1_X -o "$PHP_VERSION" = nightly ];then
        git clone --depth=1 https://github.com/php/php-src $HOME/php-src
        export PHP_VCS_REF=`git -C $HOME/php-src rev-parse --short HEAD`
        options+=' --build-arg PHP_VCS_REF'

        echo $PHP_VCS_REF
      else
        true
      fi
    else
      true
    fi
  - |
    if [ -n "$UNIT" ];then \
      set -x ; \
      docker buildx build $options \
      --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
      -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-unit-alpine \
      --cache-from=${CACHE_IMAGE}:${FOLDER}-arm-unit-cache \
      --cache-to=${CACHE_IMAGE}:${FOLDER}-arm-unit-cache \
      ${IS_PUSH} ${FOLDER}/unit; \
    fi
  - |
    if [ -n "$SUPERVISORD" ];then \
      set -x ; \
      docker buildx build $options \
      --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
      -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-supervisord-alpine \
      --cache-from=${CACHE_IMAGE}:${FOLDER}-arm-supervisord-cache \
      --cache-to=${CACHE_IMAGE}:${FOLDER}-arm-supervisord-cache \
      ${IS_PUSH} ${FOLDER}/supervisord; \
    fi
  - |
    if [ -n "$COMPOSER" ];then \
      set -x ; \
      docker buildx build $options \
      --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
      -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-composer-alpine \
      --cache-from=${CACHE_IMAGE}:${FOLDER}-arm-composr-cache \
      --cache-to=${CACHE_IMAGE}:${FOLDER}-arm-composer-cache \
      --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/composer; \
    fi
  - |
    if [ -n "$SINGLE" ];then \
       set -x ; \
       docker buildx build $options \
       --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
       -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-single-alpine \
       ${IS_PUSH} ${FOLDER}/single; \
    fi
  - |
    if [ -n "$SWOOLE" ];then \
      set -x ; \
      docker buildx build $options \
      --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
      -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-swoole-alpine \
      --cache-from=${CACHE_IMAGE}:${FOLDER}-arm-swoole-cache \
      --cache-to=${CACHE_IMAGE}:${FOLDER}-arm-swoole-cache \
      ${IS_PUSH} ${FOLDER}/swoole; \
    fi
  - |
    if [ -n "$FPM" ];then \
      set -x ; \
      docker buildx build $options \
      --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
      --target=php \
      -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-fpm-alpine \
      --cache-from=${CACHE_IMAGE}:${FOLDER}-arm-fpm-cache \
      --cache-to=${CACHE_IMAGE}:${FOLDER}-arm-fpm-cache \
      ${fpmTagOptions} --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/fpm; \
    fi
  - |
    if [ -n "$CLI" ];then \
      set -x ; \
      docker buildx build $options \
      --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} \
      -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-cli-alpine \
      --cache-from=${CACHE_IMAGE}:${FOLDER}-arm-cli-cache \
      --cache-to=${CACHE_IMAGE}:${FOLDER}-arm-cli-cache \
      --platform ${PLATFORM} \
      ${IS_PUSH} ${FOLDER}/cli; \
    fi

after_success:
  - curl -X POST https://hooks.microbadger.com/images/$DOCKER_HUB_USERNAME/php/OMVCEKSr9I0cjhU0DQop3HwjYAc=

# branches:
#   only:
#   - master
#   - dev

env:
  matrix:
  # - PHP_VERSION=5_6_X FOLDER=5.6 PHP_TAG_VERSION=5.6.40 FPM=1
  # - PHP_VERSION=7_0_X FOLDER=7.0 PHP_TAG_VERSION=7.0.33 FPM=1
  # - PHP_VERSION=7_1_X FOLDER=7.1 PHP_TAG_VERSION=7.1.33 FPM=1

  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.34 CLI=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.34 FPM=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.34 SWOOLE=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.34 UNIT=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.34 SUPERVISORD=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.34 COMPOSER=1
  # - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.34 SINGLE=1

  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.24 CLI=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.24 FPM=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.24 SWOOLE=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.24 UNIT=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.24 SUPERVISORD=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.24 COMPOSER=1

  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.12 CLI=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.12 FPM=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.12 SWOOLE=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.12 UNIT=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.12 SUPERVISORD=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.12 COMPOSER=1

  - PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 CLI=1
  - PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 FPM=1
  - PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 SWOOLE=1
  - PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 COMPOSER=1
  - PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 UNIT=1

  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly CLI=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly FPM=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly SWOOLE=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly COMPOSER=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly UNIT=1

  global:
  - DOCKER_COMPOSE_VERSION=1.27.0
  - DOCKER_BUILDKIT=1
  - DOCKER_CHANNEL=test # stable test nightly
  - DOCKER_HUB_USERNAME=khs1994
  - DOCKER_CLI_EXPERIMENTAL=enabled
  # - PLATFORM=linux/amd64,linux/arm64,linux/arm/v7
  - PLATFORM=linux/arm64,linux/arm/v7

matrix:
  fast_finish: true
  allow_failures:
  # - env: PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.34 SINGLE=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 CLI=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 FPM=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 SWOOLE=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 COMPOSER=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0RC3 UNIT=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly CLI=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly FPM=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly SWOOLE=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly COMPOSER=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly UNIT=1
