version: ~> 1.0

language: bash

os: linux
dist: xenial

services:
- docker

before_install:
- env
# 升级 Docker 最新 stable
- docker --version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) ${DOCKER_CHANNEL}"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker --version
# 升级最新 Docker Compose
- docker-compose --version
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
# ubuntu 14.04
# - echo 'DOCKER_OPTS="--experimental"' | sudo tee /etc/default/docker
# - sudo service docker restart
# ubuntu 16.04
- sudo mkdir -p /etc/systemd/system/docker.service.d
- echo -e '[Service]\nExecStart=\nExecStart=/usr/bin/dockerd' | sudo tee /etc/systemd/system/docker.service.d/docker.conf
- echo '{"hosts":["unix:///var/run/docker.sock","tcp://0.0.0.0:2375"],"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo systemctl daemon-reload
- sudo systemctl cat docker
- sudo systemctl restart docker
- sleep 5
- docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
- cat /proc/sys/fs/binfmt_misc/qemu-aarch64
- docker buildx create --name mybuilder
- docker buildx use mybuilder
- docker buildx inspect --bootstrap

script:
  - cp .env.example .env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker-compose build ${PHP_VERSION} --parallel
  # - source tag.sh

  - VCS_REF=`git rev-parse --short HEAD`
  - options="--build-arg VCS_REF=$VCS_REF"
  - echo $options

  - if [ -z "$TRAVIS_TAG" ];then if [ "$PHP_VERSION" = 8_0_X -o "$PHP_VERSION" = nightly ];then true;else true;fi;else true; fi
  - if [ -n "$UNIT" ];then docker buildx build $options --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-unit-alpine ${IS_PUSH} ${FOLDER}/unit; fi
  - if [ -n "$SUPERVISORD" ];then docker buildx build $options --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-supervisord-alpine ${IS_PUSH} ${FOLDER}/supervisord; fi
  - if [ -n "$COMPOSER" ];then docker buildx build $options --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-composer-alpine --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/composer; fi
  - if [ -n "$SINGLE" ];then docker buildx build $options --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-single-alpine ${IS_PUSH} ${FOLDER}/single; fi
  - if [ -n "$SWOOLE" ];then docker buildx build $options --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-swoole-alpine ${IS_PUSH} ${FOLDER}/swoole; fi
  - if [ -n "$FPM" ];then docker buildx build $options --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} --target=php -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-fpm-alpine ${fpmTagOptions} --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/alpine; fi
  - if [ -n "$CLI" ];then docker buildx build $options --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-cli-alpine --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/cli; fi
  - if [ -n "$PPM" ];then docker buildx build $options --build-arg ALPINE_URL=${ALPINE_URL:-dl-cdn.alpinelinux.org} -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-ppm-alpine --platform ${PLATFORM} ${IS_PUSH} ${FOLDER}/ppm; fi

after_success:
  - curl -X POST https://hooks.microbadger.com/images/$DOCKER_HUB_USERNAME/php/OMVCEKSr9I0cjhU0DQop3HwjYAc=

# branches:
#   only:
#   - master
#   - dev

env:
  matrix:
  # - PHP_VERSION=5_6_X FOLDER=5.6 PHP_TAG_VERSION=5.6.40 FPM=1
  # - PHP_VERSION=7_0_X FOLDER=7.0 PHP_TAG_VERSION=7.0.33 FPM=1
  # - PHP_VERSION=7_1_X FOLDER=7.1 PHP_TAG_VERSION=7.1.33 FPM=1

  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 CLI=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 FPM=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 SWOOLE=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 UNIT=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 SUPERVISORD=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 COMPOSER=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 PPM=1
  # - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 SINGLE=1

  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.15 CLI=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.15 FPM=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.15 SWOOLE=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.15 UNIT=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.15 SUPERVISORD=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.15 COMPOSER=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.15 PPM=1

  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.3 CLI=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.3 FPM=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.3 SWOOLE=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.3 UNIT=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.3 SUPERVISORD=1
  - PHP_VERSION=7_4_X FOLDER=7.4 PHP_TAG_VERSION=7.4.3 COMPOSER=1

  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly CLI=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly FPM=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly SWOOLE=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly COMPOSER=1

  global:
  - DOCKER_COMPOSE_VERSION=1.23.2
  - DOCKER_BUILDKIT=1
  - DOCKER_CHANNEL=test # stable test nightly
  - DOCKER_HUB_USERNAME=khs1994
  - DOCKER_CLI_EXPERIMENTAL=enabled
  # - PLATFORM=linux/amd64,linux/arm64,linux/arm/v7
  - PLATFORM=linux/amd64

matrix:
  fast_finish: true
  allow_failures:
  # - env: PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.28 SINGLE=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0test CLI=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0test FPM=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0test SWOOLE=1
  - env: PHP_VERSION=8_0_X FOLDER=8.0 PHP_TAG_VERSION=8.0.0test COMPOSER=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly CLI=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly FPM=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly SWOOLE=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly COMPOSER=1
