version: "3.7"

services:

  nightly:
    build:
      context: ./nightly/alpine
      args:
        PHP_VERSION: nightly
        IMAGE: alpine
        ALPINE_URL: mirrors.ustc.edu.cn
      target: php
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:nightly-fpm-alpine

  7_4_X:
    build:
      context: ./7.4/alpine
      args:
        PHP_VERSION: 7.4.3
        IMAGE: alpine
        ALPINE_URL: mirrors.ustc.edu.cn
      target: php
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_74:-7.4.3}-fpm-alpine

  7_3_X:
    build:
      context: ./7.3/alpine
      args:
        PHP_VERSION: ${PHP_VERSION_73:-7.3.15}
        IMAGE: php
        ALPINE_URL: mirrors.ustc.edu.cn
      target: php
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_73:-7.3.15}-fpm-alpine

  7_2_X:
    build:
      context: ./7.2/alpine
      args:
        PHP_VERSION: ${PHP_VERSION_72:-7.2.28}
        IMAGE: php
        ALPINE_URL: mirrors.ustc.edu.cn
      target: php
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_72:-7.2.28}-fpm-alpine

  7_1_X:
    build:
      context: ./7.1/alpine
      args:
        PHP_VERSION: ${PHP_VERSION_71:-7.1.33}
        IMAGE: php
        ALPINE_URL: mirrors.ustc.edu.cn
      target: php
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_71:-7.1.33}-fpm-alpine

  7_0_X:
    build:
      context: ./7.0/alpine
      args:
        PHP_VERSION: ${PHP_VERSION_70:-7.0.33}
        IMAGE: php
        ALPINE_URL: mirrors.ustc.edu.cn
      target: php
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_70:-7.0.33}-fpm-alpine

  5_6_X:
    build:
      context: ./5.6/alpine
      args:
        PHP_VERSION: ${PHP_VERSION_56:-5.6.40}
        IMAGE: php
        ALPINE_URL: mirrors.ustc.edu.cn
      target: php
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_56:-5.6.40}-fpm-alpine
