version: "3.7"

services:

  ruby:
     build:
       context: ruby
       args:
        ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org
     image: khs1994/builder:ruby@sha256:d8cd3d80bb100b7bd747a1d1b42f20db0d4e00a507e15b39d82bb3aa3e7bb742

  python:
     build:
       context: python
       args:
        ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org
     image: khs1994/builder:python
