version: "3.4"
services:
  php7:
    build:
      context: ../app/demo
      dockerfile: Dockerfile
    image: khs1994/php-fpm:swarm-7.2.0-alpine3.7

  nginx:
    build:
      context: ../config/nginx
      dockerfile: Dockerfile
    image: khs1994/nginx:swarm-1.13.7-alpine
