apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-env
  labels:
    app: lnmp
data:
  APP_ENV: development
  APP_LOG: errorlog
  LOG_CHANNEL: errorlog
  LNMP_XDEBUG_REMOTE_HOST: 192.168.199.100
  LNMP_XDEBUG_REMOTE_PORT: "9003"
  LNMP_OPCACHE_ENABLE: "1"

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: lnmp-tz
  labels:
    app: lnmp
data:
  TZ: Asia/Shanghai

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-redis-conf
  labels:
    app: lnmp
data:
  redis.conf: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
