kind: Service
apiVersion: v1
metadata:
  name: php7
  labels:
    app: lnmp
    tier: php7
    version: 0.0.1
spec:
  selector:
    app: lnmp
    tier: php7
    version: 0.0.1
  ports:
  - name: php-fpm
    port: 9000
  # clusterIP: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: php7
  labels:
    app: lnmp
    tier: php7
    version: 0.0.1
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: php7
      version: 0.0.1
  replicas: 2
  minReadySeconds: 5
  revisionHistoryLimit: 5 # 保留几个版本
  strategy:
    type: RollingUpdate # Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: lnmp
        tier: php7
        version: 0.0.1
    spec:
      containers:
      - name: lnmp-php7
        image: khs1994/php:7.4.3-fpm-alpine
        imagePullPolicy: IfNotPresent
        args:
        - php-fpm
        - -R
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: lnmp-tz
              key: TZ
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: APP_ENV
        - name: APP_LOG
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: APP_LOG
        - name: LOG_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: LOG_CHANNEL
        - name: LNMP_OPCACHE_ENABLE
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: LNMP_OPCACHE_ENABLE
        - name: LNMP_XDEBUG_REMOTE_HOST
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: LNMP_XDEBUG_REMOTE_HOST
        - name: LNMP_XDEBUG_REMOTE_PORT
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: LNMP_XDEBUG_REMOTE_PORT
        ports:
        - containerPort: 9000
          name: php-fpm
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: lnmp-app
          mountPath: /app
        - name: lnmp-php-conf
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
        - name: lnmp-php-conf
          mountPath: /usr/local/etc/php/conf.d/docker.ini
          subPath: docker.ini
        - name: lnmp-php-conf
          mountPath: /usr/local/etc/php-fpm.d/zz-docker.conf
          subPath: zz-docker.conf
        - name: lnmp-php-conf
          mountPath: /tmp/config.json
          subPath: config.json
        - name: lnmp-php-log
          mountPath: /var/log
      restartPolicy: Always
      volumes:
      - name: lnmp-php-log
        # hostPath:
        #   path: /var/log/php
        persistentVolumeClaim:
          claimName: lnmp-log
      - name: lnmp-app
        persistentVolumeClaim:
          claimName: lnmp-app
      - name: lnmp-php-conf
        configMap:
          name: lnmp-php-conf-0.0.1
          items:
          - key: php.ini
            path: php.ini
          - key: docker.ini
            path: docker.ini
          - key: zz-docker.conf
            path: zz-docker.conf
          - key: composer.config.json
            path: config.json
