# 请求头包含 foo: bar 路由到 v2，其他情况路由到 v1

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-vs-demo
spec:
  gateways:
  - demo-gw
  hosts:
  - "*"
  http:
  - match:
    - headers:
        foo:
          exact: bar
    route:
    - destination:
        host: nginx
        subset: v2
  - route:
    - destination:
        host: nginx
        subset: v1
