bases:
  - "../docker-desktop"
patchesJson6902:
  - path: service.patch.json
    target:
      kind: Service
      name: ingress-nginx-controller
      version: v1
      namespace: ingress-nginx
      group: ""
  # 默认的部署文件不会代理 tcp，这里增加该功能
  - path: controller.patch.json
    target:
      kind: Deployment
      group: apps
      version: v1
      namespace: ingress-nginx
      name: ingress-nginx-controller
