name: crictl
version: 1.21.0
url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v${VERSION}/crictl-v${VERSION}-${env:lwpm_os}-${env:lwpm_architecture}.tar.gz"
url-mirror: https://download.fastgit.org/kubernetes-sigs/cri-tools/releases/download/v${VERSION}/crictl-v${VERSION}-${env:lwpm_os}-${env:lwpm_architecture}.tar.gz
command: crictl
scripts:
  dist: |
    _mkdir $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}

    curl -L `
      $url `
      -o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/$filename
  install:
    if($IsWindows){tar -zxf $filename -C C:\bin}else{sudo tar -zxf $filename -C /usr/local/bin}
  version: (crictl --version).split(' ')[2].trim('v')
  uninstall: _cleanup C:\bin\crictl.exe
  test: crictl --version
  platform-reqs: if($IsMacOs){echo $False}
platform:
  - architecture: amd64
    os: windows
    hash:
      sha256: 5045bcc6d8b0e6004be123ab99ea06e5b1b2ae1e586c968fcdf85fccd4d67ae1
  - architecture: amd64
    os: linux
  - architecture: arm64
    os: linux
  - architecture: arm
    os: linux
