bases:
- ./rbac
resources:
- namespace.yaml
- csi-hostpath-attacher.yaml
- csi-hostpath-driverinfo.yaml
- csi-hostpath-plugin.yaml
- csi-hostpath-provisioner.yaml
- csi-hostpath-resizer.yaml
- csi-hostpath-snapshotter.yaml
- csi-hostpath-snapshotclass.yaml
- sc.yaml
namespace: csi-hostpath
