kind: Pod
apiVersion: v1
metadata:
  name: test
  labels:
    lnmp: test
spec:
  # runtimeClassName: runsc
  runtimeClassName: runc
  # runtimeClassName: runcv1
  # runtimeClassName: runclinux
  containers:
  - name: "lnmp-pod"
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test
      mountPath: /opt/data
  # - name: "lnmp-pod2"
  #   image: khs1994/php:7.4.1-fpm-alpine
  volumes:
  - name: test
    emptyDir: {}
