apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
# Fix me
bindAddress: 192.168.199.100
clientConnection:
  kubeconfig: /opt/bin/k8s/conf/kube-proxy.kubeconfig
clusterCIDR: 172.30.0.0/16 # ${CLUSTER_CIDR}
# Fix me
healthzBindAddress: 192.168.199.100:10256
# Fix me
hostnameOverride: node1
# Fix me
metricsBindAddress: 192.168.199.100:10249
mode: "ipvs"
