version: "3.7"

services:

  arm64v8-php-fpm:
    build:
      context: .
      args:
        ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/arm64v8-php:${TAG:-7.2.13}-fpm-alpine
