

x-common:
  &common
  restart: always
  env_file: ./cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  minio-old:
    << : *common
    image: minio/minio:${LNMP_MINIO_OLD_VERSION:-RELEASE.2022-10-24T18-35-07Z}
    volumes:
      - type: volume
        source: minio-old-data
        target: /data
      # - ./config/nginx/demo-ssl/t.khs1994.com.crt:/root/.minio/certs/public.crt
      # - ./config/nginx/demo-ssl/t.khs1994.com.key:/root/.minio/certs/private.key
    ports:
      - "19000:9000"
      - "19090:9090"
    environment:
      # https://github.com/minio/minio/blob/master/docs/config/README.md
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME:-us-east-1}
      MINIO_BROWSER: ${MINIO_BROWSER:-on}
      MINIO_DOMAIN: ${MINIO_DOMAIN:-''}
    command:
      - server
      - /data
      - --console-address
      - ':9090'
      - --address
      - ':9000'
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 3
      timeout: 5s

volumes:
  minio-old-data:
    << : *common-label
