apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  annotations:
        "volume.alpha.kubernetes.io/node-affinity": '{
            "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                    { "matchExpressions": [
                        { "key": "kubernetes.io/hostname",
                          "operator": "In",
                          "values": ["node-name"]
                        }
                    ]}
                 ]}
              }'
spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
      path: /mnt/disks/ssd1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: lnmp-pod
  labels:
    app: lnmp
spec:
  containers:
  - name: "lnmp-pod"
    image: "khs1994/nginx:1.15.7-alpine"
    volumeMounts:
    - name: lnmp-data
      mountPath: /app
  volumes:
  - name: lnmp-data
    hostPath:
      path: /data/lnmp/app
