version: "3.8"
services:

  nginx:
    container_name: config_nginx_1_666
    image: nginx:${LNMP_NGINX_VERSION}-alpine

  httpd:
    container_name: config_httpd_1_666
    image: httpd:${LNMP_HTTPD_VERSION}-alpine

  mysql:
    container_name: config_mysql_1_666
    image: mysql:${LNMP_MYSQL_VERSION}

  mariadb:
    container_name: config_mariadb_1_666
    image: mariadb:${LNMP_MARIADB_VERSION}

  php7:
    container_name: config_php7_1_666
    image: khs1994/php:${LNMP_PHP_VERSION}-fpm-alpine

  php8:
    container_name: config_php8_1_666
    image: khs1994/php:${LNMP_PHP8_VERSION}-fpm-alpine
