version: "3.8"

services:
  nginx:
    build:
      context: nginx
      args:
        WIN_VERSION: ${WIN_VERSION:-/servercore:1903}
    image: khs1994/nginx:1.17.3-windowsservercore-1903

  mysql:
    build:
      context: mysql
      args:
        WIN_VERSION: ${WIN_VERSION:-/servercore:1903}
    image: khs1994/mysql:8.0.17-windowsservercore-1903

  php:
    build:
      context: php
      args:
        WIN_VERSION: ${WIN_VERSION:-/servercore:1903}
    image: khs1994/php:7.3.8-windowsservercore-1903
