apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-mysql-data
  labels:
    app: lnmp
    tier: mysql
    env: development
spec:
  accessModes:
    - ReadWriteOnce
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
      env: development
    # matchExpressions:
      # - {key: environment, operator: In, values: [dev]}
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-redis-data
  labels:
    app: lnmp
    tier: redis
    env: development
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: redis
      env: development
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-app
  labels:
    app: lnmp
    tier: code-data
    env: development
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: code-data
      env: development
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-registry-data
  labels:
    app: lnmp
    tier: registry
    env: development
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: registry
      env: development
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-log
  labels:
    app: lnmp
    tier: log
    env: development
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: log
      env: development
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
