version: "3.7"

services:
  k8s_apiserver:
    image: k8s.gcr.io/kube-apiserver:v1.17.0

  k8s_dashboard:
    image: kubernetesui/dashboard:v2.0.0-rc5

  coredns:
    image: k8s.gcr.io/coredns:1.6.7

  pause:
    image: k8s.gcr.io/pause:3.2
    # https://github.com/kubernetes/kubernetes/tree/master/build/pause

  calico:
    image: calico/cni:v3.13.1

  ingress_nginx:
    image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0

  metrics_server:
    image: k8s.gcr.io/metrics-server-amd64:v0.3.6
