

services:
  k8s_apiserver:
    image: k8s.gcr.io/kube-apiserver:v1.25.0

  etcd:
    image: quay.io/coreos/etcd:v3.5.4

  k8s_dashboard:
    image: kubernetesui/dashboard:v2.6.0

  coredns:
    image: registry.k8s.io/coredns/coredns:v1.9.3

  pause:
    image: k8s.gcr.io/pause:3.7
    # https://github.com/kubernetes/kubernetes/tree/master/build/pause

  calico:
    image: calico/cni:v3.24.0

  ingress_nginx:
    image: registry.k8s.io/ingress-nginx/controller:v1.3.0

  ingress-kong:
    image: kong/kubernetes-ingress-controller:2.5.0

  metrics_server:
    image: k8s.gcr.io/metrics-server/metrics-server:v0.6.0

  butane:
    image: quay.io/coreos/butane:v0.13.1

  php-fpm-exporter:
    image: bakins/php-fpm-exporter:v0.6.1
