version: "3.7"

services:
  k8s_apiserver:
    image: k8s.gcr.io/kube-apiserver:v1.18.0

  k8s_dashboard:
    image: kubernetesui/dashboard:v2.0.1

  k8s_dashboard_metrics-scraper:
    image: kubernetesui/metrics-scraper:v1.0.5

  coredns:
    image: k8s.gcr.io/coredns:1.6.7

  pause:
    image: k8s.gcr.io/pause:3.2
    # https://github.com/kubernetes/kubernetes/tree/master/build/pause

  calico:
    image: calico/cni:v3.14.0

  ingress_nginx:
    image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0

  ingress-kong:
    image: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.0

  metrics_server:
    image: k8s.gcr.io/metrics-server-amd64:v0.3.6
