version: "3.7"

services:
  mysql:
    image: mysql:8.0.18

  mariadb:
    image: mariadb:10.4.10

  redis:
    image: redis:5.0.7-alpine

  memcached:
    image: memcached:1.5.20-alpine

  php:
    image: php:7.4.0-fpm-alpine

  composer:
    image: composer:1.9.1

  nginx:
    image: nginx:1.17.6-alpine

  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine

  postgresql:
    image: postgres:12.1-alpine

  mongodb:
    image: mongo:4.2.1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

  httpd:
    image: httpd:2.4.41-alpine

  etcd:
    image: quay.io/coreos/etcd:3.4.3

  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z

  kong:
    image: kong:1.4.2-alpine

  node:
    image: node:13.3.0-alpine

  go:
    image: golang:1.13.5-alpine

  alpine:
    image: alpine:3.10

  python:
    image: python:3.8.0-alpine
