version: "3.7"

services:
  mysql:
    image: mysql:8.0.21

  mariadb:
    image: mariadb:10.5.4

  redis:
    image: redis:6.0.6-alpine

  memcached:
    image: memcached:1.6.6-alpine

  php:
    image: php:7.4.8-fpm-alpine

  composer:
    image: composer:1.10.9

  nginx:
    image: nginx:1.19.1-alpine

  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine

  postgresql:
    image: postgres:12.3-alpine

  mongodb:
    image: mongo:4.4.0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

  httpd:
    image: httpd:2.4.43-alpine

  etcd:
    image: quay.io/coreos/etcd:v3.4.10

  minio:
    image: minio/minio:RELEASE.2020-07-31T03-39-05Z

  kong:
    image: kong:2.1.0-alpine

  node:
    image: node:14.7.0-alpine

  go:
    image: golang:1.14.7-alpine

  alpine:
    image: alpine:3.12

  python:
    image: python:3.8.5-alpine

  docker-binfmt:
    image: docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64

  docker:
    image: docker:19.03.12
