version: "3.9"

services:
  mysql:
    image: mysql:8.0.26

  mariadb:
    image: mariadb:10.6.4

  redis:
    image: redis:6.2.5-alpine

  memcached:
    image: memcached:1.6.10-alpine

  php:
    image: php:8.0.12-fpm-alpine

  composer:
    image: composer:2.2.4

  nginx:
    image: nginx:1.21.3-alpine

  rabbitmq:
    image: rabbitmq:3.9.0-management-alpine

  postgresql:
    image: postgres:14.0-alpine

  mongodb:
    image: mongo:5.0.3

  phpmyadmin:
    image: phpmyadmin:5.1.1

  httpd:
    image: httpd:2.4.49-alpine

  etcd:
    image: quay.io/coreos/etcd:v3.5.1

  minio:
    image: minio/minio:RELEASE.2021-07-08T01-15-01Z

  kong:
    image: kong:2.5.1-alpine

  node:
    image: node:16.10.0-alpine

  go:
    image: golang:1.16.6-alpine

  alpine:
    image: alpine:3.14

  python:
    image: python:3.9.5-alpine

  deno:
    image: denoland/deno:1.14.2

  docker-binfmt:
    image: tonistiigi/binfmt:latest

  docker:
    image: docker:20.10.8

  gogs:
    image: gogs/gogs:0.12

  acme.sh:
    image: neilpang/acme.sh:3.0.0
