version: "3.7"

services:
  mysql:
    image: mysql:8.0.19

  mariadb:
    image: mariadb:10.5.2

  redis:
    image: redis:5.0.8-alpine

  memcached:
    image: memcached:1.6.3-alpine

  php:
    image: php:7.4.4-fpm-alpine

  composer:
    image: composer:1.10.1

  nginx:
    image: nginx:1.17.9-alpine

  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine

  postgresql:
    image: postgres:12.2-alpine

  mongodb:
    image: mongo:4.2.5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

  httpd:
    image: httpd:2.4.43-alpine

  etcd:
    image: quay.io/coreos/etcd:3.4.6

  minio:
    image: minio/minio:RELEASE.2020-03-25T07-03-04Z

  kong:
    image: kong:2.0.2-alpine

  node:
    image: node:13.12.0-alpine

  go:
    image: golang:1.14.1-alpine

  alpine:
    image: alpine:3.11

  python:
    image: python:3.8.2-alpine
