version: "3.7"

services:
  mysql:
    image: mysql:8.0.21

  mariadb:
    image: mariadb:10.5.6

  redis:
    image: redis:6.0.8-alpine

  memcached:
    image: memcached:1.6.7-alpine

  php:
    image: php:7.4.11-fpm-alpine

  composer:
    image: composer:1.10.13

  nginx:
    image: nginx:1.19.3-alpine

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine

  postgresql:
    image: postgres:13.0-alpine

  mongodb:
    image: mongo:4.4.1

  phpmyadmin:
    image: phpmyadmin:5.0.2

  httpd:
    image: httpd:2.4.46-alpine

  etcd:
    image: quay.io/coreos/etcd:v3.4.13

  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z

  kong:
    image: kong:2.1.4-alpine

  node:
    image: node:14.14.0-alpine

  go:
    image: golang:1.15.3-alpine

  alpine:
    image: alpine:3.12

  python:
    image: python:3.9.0-alpine

  docker-binfmt:
    image: tonistiigi/binfmt:latest

  docker:
    image: docker:19.03.13

  gogs:
    image: gogs/gogs:0.12
