version: "3.9"

services:
  mysql:
    image: mysql:8.0.25

  mariadb:
    image: mariadb:10.6.1

  redis:
    image: redis:6.2.4-alpine

  memcached:
    image: memcached:1.6.9-alpine

  php:
    image: php:8.0.7-fpm-alpine

  composer:
    image: composer:2.1.3

  nginx:
    image: nginx:1.21.0-alpine

  rabbitmq:
    image: rabbitmq:3.8.17-management-alpine

  postgresql:
    image: postgres:13.3-alpine

  mongodb:
    image: mongo:4.4.6

  phpmyadmin:
    image: phpmyadmin:5.1.1

  httpd:
    image: httpd:2.4.48-alpine

  etcd:
    image: quay.io/coreos/etcd:v3.5.0

  minio:
    image: minio/minio:RELEASE.2021-01-30T00-20-58Z

  kong:
    image: kong:2.4.1-alpine

  node:
    image: node:16.3.0-alpine

  go:
    image: golang:1.16.5-alpine

  alpine:
    image: alpine:3.13

  python:
    image: python:3.9.5-alpine

  docker-binfmt:
    image: tonistiigi/binfmt:latest

  docker:
    image: docker:20.10.7

  gogs:
    image: gogs/gogs:0.12
