

services:
  mysql:
    image: mysql:8.0.30

  mariadb:
    image: mariadb:10.8.3

  redis:
    image: redis:7.0.0-alpine

  memcached:
    image: memcached:1.6.15-alpine

  php:
    image: php:8.2.2-fpm-alpine

  composer:
    image: composer:2.5.5

  nginx:
    image: nginx:1.23.3-alpine

  nginx-unit:
    image: docker.io/nginx/unit:1.28.0-minimal

  rabbitmq:
    image: rabbitmq:3.9.0-management-alpine

  postgresql:
    image: postgres:14.0-alpine

  mongodb:
    image: mongo:5.0.3

  phpmyadmin:
    image: phpmyadmin:5.2.0

  httpd:
    image: httpd:2.4.53-alpine

  minio:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z

  kong:
    image: kong:2.8.1-alpine

  node:
    image: node:18.2.0-alpine

  go:
    image: golang:1.20.1-alpine

  alpine:
    image: alpine:3.16

  python:
    image: python:3.11.1-alpine

  deno:
    image: denoland/deno:1.31.1

  docker-binfmt:
    image: tonistiigi/binfmt:latest

  docker:
    image: docker:23.0.5

  gogs:
    image: gogs/gogs:0.13

  acme.sh:
    image: neilpang/acme.sh:3.0.0
