version: "3.7"

services:
  mysql:
    image: mysql:8.0.16

  mariadb:
    image: mariadb:10.4.6

  redis:
    image: redis:5.0.5-alpine

  memcached:
    image: memcached:1.5-alpine

  php:
    image: php:7.3.7-fpm-alpine

  nginx:
    image: nginx:1.17.1-alpine

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine

  postgresql:
    image: postgres:11.5-alpine

  mongodb:
    image: mongo:4.1.13

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

  httpd:
    image: httpd:2.4.39-alpine

  etcd:
    image: quay.io/coreos/etcd:3.3.13

  minio:
    image: minio/minio:RELEASE.2019-07-05T21-20-21Z

  kong:
    image: kong:1.2.1-alpine

  node:
    image: node:12.6.0-alpine

  go:
    image: golang:1.12.7-alpine

  alpine:
    image: alpine:3.10

  python:
    image: python:3.7.4-alpine
