version: "3.7"

services:
  mysql:
    image: mysql:8.0.17

  mariadb:
    image: mariadb:10.4.7

  redis:
    image: redis:5.0.5-alpine

  memcached:
    image: memcached:1.5.17-alpine

  php:
    image: php:7.3.9-fpm-alpine

  nginx:
    image: nginx:1.17.3-alpine

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine

  postgresql:
    image: postgres:11.4-alpine

  mongodb:
    image: mongo:4.1.13

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

  httpd:
    image: httpd:2.4.41-alpine

  etcd:
    image: quay.io/coreos/etcd:3.4.0

  minio:
    image: minio/minio:RELEASE.2019-09-05T23-24-38Z

  kong:
    image: kong:1.3.0-alpine

  node:
    image: node:12.10.0-alpine

  go:
    image: golang:1.13.0-alpine

  alpine:
    image: alpine:3.10

  python:
    image: python:3.7.4-alpine
