version: "3.8"

services:
  mysql:
    image: mysql:8.0.23

  mariadb:
    image: mariadb:10.5.9

  redis:
    image: redis:6.2.1-alpine

  memcached:
    image: memcached:1.6.9-alpine

  php:
    image: php:8.0.3-fpm-alpine

  composer:
    image: composer:2.0.11

  nginx:
    image: nginx:1.19.7-alpine

  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine

  postgresql:
    image: postgres:13.2-alpine

  mongodb:
    image: mongo:4.4.4

  phpmyadmin:
    image: phpmyadmin:5.1.0

  httpd:
    image: httpd:2.4.46-alpine

  etcd:
    image: quay.io/coreos/etcd:v3.4.15

  minio:
    image: minio/minio:RELEASE.2021-01-30T00-20-58Z

  kong:
    image: kong:2.3.2-alpine

  node:
    image: node:15.11.0-alpine

  go:
    image: golang:1.16.0-alpine

  alpine:
    image: alpine:3.13

  python:
    image: python:3.9.2-alpine

  docker-binfmt:
    image: tonistiigi/binfmt:latest

  docker:
    image: docker:20.10.5

  gogs:
    image: gogs/gogs:0.12
