# Default values for lnmp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

example:
  enabled: false

nameOverride: "nginx-php"
fullnameOverride: "fullname"

TZ: Asia/Shanghai

APP_ENV: production
# laravel 5.5
APP_LOG: errorlog
# laravel 5.6+
LOG_CHANNEL: errorlog

platform: Linux
# platform: windows
# platform: Darwin

domain: t.khs1994.com

nfs:
  enabled: false
  server: 192.168.199.100

nginx:
  image: khs1994/nginx:1.15.7-alpine
  replicaCount: 2

php:
  image: khs1994/php:7.2.13-fpm-alpine
  replicaCount: 2

cronjob:
  enabled: false

################################################################################

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # type: NodePort
  # type: LoadBalancer
  port: 80

ingress:
  enabled: false
  # annotations: {}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
