version: "3.5"
services:

  7_2_X:
    build:
      context: ./7.2/alpine3.7
      args:
        PHP_VERSION: ${PHP_VERSION_72:-7.2.6}
        ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php-fpm:${PHP_VERSION_72:-7.2.6}-alpine3.7

  7_1_X:
    build:
      context: ./7.1/alpine3.7
      args:
        PHP_VERSION: ${PHP_VERSION_71:-7.1.18}
        # ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php-fpm:${PHP_VERSION_71:-7.1.18}-alpine
