apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "harbor-ingress"
  labels:
    heritage: Helm
    release: RELEASE-NAME
    chart: harbor
    app: "harbor"
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: kong
  tls:
  # fix me
  - secretName: cert.t.khs1994.com
    hosts:
    - harbor.t.khs1994.com
    - notary-harbor.t.khs1994.com
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: harbor-portal
          servicePort: 80
      - path: /api/
        backend:
          serviceName: harbor-core
          servicePort: 80
      - path: /service/
        backend:
          serviceName: harbor-core
          servicePort: 80
      - path: /v2/
        backend:
          serviceName: harbor-core
          servicePort: 80
      - path: /chartrepo/
        backend:
          serviceName: harbor-core
          servicePort: 80
      - path: /c/
        backend:
          serviceName: harbor-core
          servicePort: 80
    host: harbor.t.khs1994.com
  - http:
      paths:
      - path: /
        backend:
          serviceName: harbor-notary-server
          servicePort: 4443
    host: notary-harbor.t.khs1994.com
