name: lwpm-dist-k8s-file

on:
  push:
    branches:
      - bump-k8s

jobs:
  lwpm-dist-k8s-file:
    name: lwpm-dist-k8s-file
    runs-on: ${{ matrix.os }}-latest
    env:
      LWPM_K8S_VERSION: "1.19.0-beta.0"

      LWPM_DOCKER_USERNAME: khs1994
      LWPM_DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      LWPM_DIST_ONLY: 'true'
      LWPM_DOCKER_REGISTRY: registry-1.docker.io
      DOCKER_ROOTFS_PHASE: "manifest list"
    strategy:
      matrix:
        os: ["windows","ubuntu"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          repository: khs1994-docker/lnmp
          fetch-depth: 1
          path: lnmp
      - name: handle-kubectl
        shell: pwsh
        if: matrix.os == 'windows'
        run: |
          echo $ErrorActionPreference
          $ErrorActionPreference = "Continue"

          ./lnmp/windows/lnmp-windows-pm.ps1 install kubectl@${env:LWPM_K8S_VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    kubectl@${env:LWPM_K8S_VERSION}

          . ./lnmp/windows/sdk/dockerhub/rootfs.ps1
          rootfs lwpm/kubectl ${env:LWPM_K8S_VERSION}
      - name: handle-kubernetes-server
        shell: pwsh
        if: matrix.os == 'windows'
        run: |
          echo $ErrorActionPreference
          $ErrorActionPreference = "Continue"

          ./lnmp/windows/lnmp-windows-pm.ps1 install kubernetes-server@${env:LWPM_K8S_VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    kubernetes-server@${env:LWPM_K8S_VERSION}

          . ./lnmp/windows/sdk/dockerhub/rootfs.ps1
          rootfs lwpm/kubernetes-server ${env:LWPM_K8S_VERSION}
      - name: handle-kubernetes-node
        shell: pwsh
        if: matrix.os == 'ubuntu'
        run: |
          Import-Alias ./lnmp/windows/pwsh-alias.txt -Force

          ./lnmp/windows/lnmp-windows-pm.ps1 install kubernetes-node@${env:LWPM_K8S_VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    kubernetes-node@${env:LWPM_K8S_VERSION}

          . ./lnmp/windows/sdk/dockerhub/rootfs.ps1
          rootfs lwpm/kubernetes-node ${env:LWPM_K8S_VERSION}
  trigger-coding-net-ci:
    needs: lwpm-dist-k8s-file
    name: trigger-coding-net-ci
    runs-on: ubuntu-latest
    env:
      LWPM_K8S_VERSION: "1.19.0-beta.0"
    steps:
      - name: trigger-coding.net-ci
        env:
          CODING_PASSWORD: ${{secrets.CODING_LWPM_K8S_CI_PASSWORD}}
        run: |
          set -x
          curl -u pto8bv6hoj8e:${CODING_PASSWORD} \
          -v -X POST  'https://pcit.coding.net/api/cci/job/234348/trigger' \
          -H 'Content-Type: application/json' \
          -d "
          {
            \"ref\": \"master\",
            \"envs\": [
              {
                \"name\": \"LWPM_K8S_VERSION\",
                \"value\": \"${LWPM_K8S_VERSION}\",
                \"sensitive\": 0
              }
            ]
          }"
